DROP SCHEMA IF EXISTS `recon`;

CREATE SCHEMA `recon` DEFAULT CHARACTER SET utf8;

USE `recon`;

--oracle
select sys_context('USERENV', 'CURRENT_SCHEMA') from dual;

--Oracle10g
ALTER TABLE RECONLOG 
ADD (JOB_RUN_DATE DATE, STATUS VARCHAR2(40), PRIOR_STATUS VARCHAR2(40));


INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (1, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME1', 'LNAME1', 'ACCOUNT1', 'SUBS1', 'TXN1', 'REG1', 'CITY1', 'A', 'no-reply@domain.com', 'NOT_STARTED');
INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (2, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME2', 'LNAME2', 'ACCOUNT2', 'SUBS2', 'TXN2', 'REG2', 'CITY2', 'D', 'no-reply@domain.com', 'COMPLETED');
INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (3, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME3', 'LNAME3', 'ACCOUNT3', 'SUBS3', 'TXN3', 'REG3', 'CITY3', 'F', 'no-reply@domain.com', 'NOT_STARTED');
INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (4, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME4', 'LNAME4', 'ACCOUNT4', 'SUBS4', 'TXN4', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'COMPLETED');
INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (5, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME5', 'LNAME5', 'ACCOUNT5', 'SUBS5', 'TXN5', 'REG3', 'CITY3', 'F', 'no-reply@domain.com', 'FAILED');
INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (6, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME6', 'LNAME6', 'ACCOUNT6', 'SUBS6', 'TXN6', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'NOT_STARTED');
INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (7, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME2', 'LNAME2', 'ACCOUNT2', 'SUBS2', 'TXN2', 'REG2', 'CITY2', 'D', 'no-reply@domain.com', 'FAILED');
INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (8, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME3', 'LNAME3', 'ACCOUNT3', 'SUBS3', 'TXN3', 'REG3', 'CITY3', 'F', 'no-reply@domain.com', 'COMPLETED');
INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (9, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME4', 'LNAME4', 'ACCOUNT4', 'SUBS4', 'TXN4', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'COMPLETED');
INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (10, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME4', 'LNAME4', 'ACCOUNT4', 'SUBS4', 'TXN4', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'COMPLETED');
INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (11, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME4', 'LNAME4', 'ACCOUNT4', 'SUBS4', 'TXN4', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'NOT_STARTED');
INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_NUMBER, SUBSCRIBER_NUMBER, TRANSACTION_NUMBER, REGISTER_NUMBER, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (12, 25, NULL, SYSDATE, SYSDATE, 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE, 'FNAME4', 'LNAME4', 'ACCOUNT4', 'SUBS4', 'TXN4', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'NOT_STARTED');
commit;

UPDATE RECONLOG SET STATUS = 'FAILED' WHERE RECON_ID IN (1,2,3);
UPDATE RECONLOG SET STATUS = 'COMPLETED' WHERE RECON_ID IN (4,5,6);
UPDATE RECONLOG SET STATUS = 'NOT_STARTED' WHERE RECON_ID IN (8,9,10);
commit;


DELETE FROM  BATCH_STEP_EXECUTION_CONTEXT ;
DELETE FROM  BATCH_JOB_EXECUTION_CONTEXT ;
DELETE FROM  BATCH_STEP_EXECUTION ;
DELETE FROM  BATCH_JOB_EXECUTION_PARAMS ;
DELETE FROM  BATCH_JOB_EXECUTION ;
DELETE FROM  BATCH_JOB_INSTANCE ;
commit;

SELECT * FROM BATCH_JOB_EXECUTION;
SELECT * FROM BATCH_JOB_EXECUTION_CONTEXT;
SELECT * FROM BATCH_JOB_EXECUTION_PARAMS;
SELECT * FROM BATCH_JOB_EXECUTION_SEQ;
SELECT * FROM BATCH_JOB_INSTANCE;
SELECT * FROM BATCH_JOB_SEQ;
SELECT * FROM BATCH_STEP_EXECUTION;
SELECT * FROM BATCH_STEP_EXECUTION_CONTEXT;
SELECT * FROM BATCH_STEP_EXECUTION_SEQ;