DROP SCHEMA IF EXISTS `recon`;

CREATE SCHEMA `recon` DEFAULT CHARACTER SET utf8;

USE `recon`;

CREATE TABLE RECONLOG (RECON_ID INT, CONTENT_TYPE INT, REQUEST_XML BLOB, REQUEST_TIME DATE, RESPONSE_TIME DATE, RESPONSE_STATUS VARCHAR(50), USERNAME VARCHAR(20), ROLE_ID INT, APPLICATION_NAME VARCHAR(10), REPONSE_XML BLOB, STORE_ID VARCHAR(20), DEALER_CODE VARCHAR(20), CREATION_DATE DATE, CUSTOMER_F_NAME VARCHAR(50), CUSTOMER_L_NAME VARCHAR(50), ACCOUNT_INT VARCHAR(9), SUBSCRIBER_INT VARCHAR(10), TRANSACTION_INT VARCHAR(25), REGISTER_INT VARCHAR(10), STORE_CITY VARCHAR(50), STORE_STATE VARCHAR(2), EMAIL_ADDRESS VARCHAR(256));

ALTER TABLE RECONLOG 
ADD COLUMN JOB_RUN_DATE DATETIME AFTER RECON_ID, 
ADD COLUMN STATUS VARCHAR(40) AFTER JOB_RUN_DATE, 
ADD COLUMN PRIOR_STATUS VARCHAR(40) AFTER STATUS;

INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (1, 25, NULL, SYSDATE(), SYSDATE(), "SUCCESS", 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME1', 'LNAME1', 'ACCOUNT1', 'SUBS1', 'TXN1', 'REG1', 'CITY1', 'A', 'no-reply@domain.com', 'NOT_STARTED');

INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (2, 25, NULL, SYSDATE(), SYSDATE(), 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME2', 'LNAME2', 'ACCOUNT2', 'SUBS2', 'TXN2', 'REG2', 'CITY2', 'D', 'no-reply@domain.com', 'COMPLETED');

INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (3, 25, NULL, SYSDATE(), SYSDATE(), 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME3', 'LNAME3', 'ACCOUNT3', 'SUBS3', 'TXN3', 'REG3', 'CITY3', 'F', 'no-reply@domain.com', 'NOT_STARTED');

INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (4, 25, NULL, SYSDATE(), SYSDATE(), 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME4', 'LNAME4', 'ACCOUNT4', 'SUBS4', 'TXN4', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'COMPLETED');


INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (5, 25, NULL, SYSDATE(), SYSDATE(), 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME5', 'LNAME5', 'ACCOUNT5', 'SUBS5', 'TXN5', 'REG3', 'CITY3', 'F', 'no-reply@domain.com', 'FAILED');

INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (6, 25, NULL, SYSDATE(), SYSDATE(), 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME6', 'LNAME6', 'ACCOUNT6', 'SUBS6', 'TXN6', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'NOT_STARTED');

INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (7, 25, NULL, SYSDATE(), SYSDATE(), 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME2', 'LNAME2', 'ACCOUNT2', 'SUBS2', 'TXN2', 'REG2', 'CITY2', 'D', 'no-reply@domain.com', 'FAILED');

INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (8, 25, NULL, SYSDATE(), SYSDATE(), 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME3', 'LNAME3', 'ACCOUNT3', 'SUBS3', 'TXN3', 'REG3', 'CITY3', 'F', 'no-reply@domain.com', 'COMPLETED');

INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (9, 25, NULL, SYSDATE(), SYSDATE(), 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME4', 'LNAME4', 'ACCOUNT4', 'SUBS4', 'TXN4', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'COMPLETED');

INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (10, 25, NULL, SYSDATE(), SYSDATE(), 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME4', 'LNAME4', 'ACCOUNT4', 'SUBS4', 'TXN4', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'COMPLETED');

INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (11, 25, NULL, SYSDATE(), SYSDATE(), 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME4', 'LNAME4', 'ACCOUNT4', 'SUBS4', 'TXN4', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'NOT_STARTED');

INSERT INTO RECONLOG (RECON_ID, CONTENT_TYPE, REQUEST_XML, REQUEST_TIME, RESPONSE_TIME, RESPONSE_STATUS, USERNAME, ROLE_ID, APPLICATION_NAME, REPONSE_XML, STORE_ID, DEALER_CODE, CREATION_DATE, CUSTOMER_F_NAME, CUSTOMER_L_NAME, ACCOUNT_INT, SUBSCRIBER_INT, TRANSACTION_INT, REGISTER_INT, STORE_CITY, STORE_STATE, EMAIL_ADDRESS, STATUS) VALUES (12, 25, NULL, SYSDATE(), SYSDATE(), 'SUCCESS', 'USER1', 3, 'APP NAME1', NULL, 'STOREID1', 'DEALERCODE1', SYSDATE(), 'FNAME4', 'LNAME4', 'ACCOUNT4', 'SUBS4', 'TXN4', 'REG4', 'CITY4', 'J', 'no-reply@domain.com', 'NOT_STARTED');

UPDATE RECONLOG SET STATUS = 'FAILED' WHERE RECON_ID IN (1,2,3);

UPDATE RECONLOG SET STATUS = 'COMPLETED' WHERE RECON_ID IN (4,5,6);

UPDATE RECONLOG SET STATUS = 'NOT_STARTED' WHERE RECON_ID IN (8,9,10);

SELECT * FROM BATCH_JOB_EXECUTION;
SELECT * FROM BATCH_JOB_EXECUTION_CONTEXT;
SELECT * FROM BATCH_JOB_EXECUTION_PARAMS;
SELECT * FROM BATCH_JOB_EXECUTION_SEQ;
SELECT * FROM BATCH_JOB_INSTANCE;
SELECT * FROM BATCH_JOB_SEQ;
SELECT * FROM BATCH_STEP_EXECUTION;
SELECT * FROM BATCH_STEP_EXECUTION_CONTEXT;
SELECT * FROM BATCH_STEP_EXECUTION_SEQ;